
"""correct field id

Revision ID: 5931337d5a6a
Revises: 9061a8720ea7
Create Date: 2025-12-10 08:14:49.176132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5931337d5a6a'
down_revision = '9061a8720ea7'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
