
"""init tables

Revision ID: 9061a8720ea7
Revises: f7947f89b433
Create Date: 2025-11-30 09:36:46.620355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9061a8720ea7'
down_revision = 'f7947f89b433'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
